"""first

Revision ID: 3d9782bdefc6
Revises: 
Create Date: 2023-10-05 19:25:21.229085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9782bdefc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_line', sa.String(), nullable=True),
    sa.Column('header', sa.String(), nullable=True),
    sa.Column('card1', sa.String(), nullable=True),
    sa.Column('card2', sa.String(), nullable=True),
    sa.Column('card3', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_line')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site')
    # ### end Alembic commands ###
